### ISSUE TITLE
Play video throws video resolving error after session cookies expiration

### ISSUE THREAD

**Issue by tommistolercz** [tommistolercz/plugin.video.vk#57]

**Comment by SingleMalt2104** [comment]
Hello Tom Mistoler,

first of all thank you for releasing v1.2.0. of your plugin. Now I was finally able to open and view/play some of my videos. I even could play a few videos of my subscribed communities after entering their subfolders.

Suddenly I am confronted with the error message of this topic:"Resolving error". As you already seem to know why this occurs ("[...] due to unhandled cookies expiration") I will simply wait for a follow up version of your plugin where said problem(s) will have been fixed. Thanks your for your continuing efforts.

best regards, SingleMalt2104

**Comment by tommistolercz** [comment]
Hello, 

to solve this issue, try these simple steps:
- go to addon settings > USER tab > click LOGOUT USER button
- close settings with OK(!), restart Kodi
- run the addon and re-login with your VK credentials

**Comment by SingleMalt2104** [comment]
Hello,

thanks for the work-around. Well, the "resolving error" occurs to me if I try playing videos of a specific community I subscribed to, which reads "Tagesschlau Community". The other community I subscribed to reads "Der Volkslehrer" from which videos do play fine. Very odd. ;)

Also the "Tagesschlau Community" which is run by "Uwe Tagesschlau" whom I befriended to in VK.com, shows only five videos. Whereas my friend "Uwe Tagesschlau" posted/uploaded until today about 372 personal videos which I would like to view as a whole package but am unable to do so, or at least don't know how. It seems I would have to add every (new) video he released to my personal videos folder first or like it/them one by one, with no possibility to "subscribe" to his personal video folder as a whole, like I am used to by using youtube. And I have to do this on my PC in a VK.com session. Or am I missing a VK.com "subscribing to a person's/friend's videos list" feature here? How would you do it?

Apart from above said problem(s) the video search for instance now works, meaning results show up and are playable, which couldn't be done before. Also the "played video history" views/plays fine. Good progress so far, much appreciated! :)

best regards, SingleMalt2104

**Comment by tommistolercz** [comment]
fixed v1.6.0
